# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-web:
    name: Build apps/web (Next.js)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: apps/web

    env:
      # Reales para CI (copiados como secrets)
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      # Solo para que el build compile en CI (placeholders)
      YAPPY_PUBLIC_API_KEY: "DUMMY"
      YAPPY_PRIVATE_API_KEY: "DUMMY"
      YAPPY_HASH_SECRET: "DUMMY"
      TWILIO_ACCOUNT_SID: "DUMMY"
      TWILIO_AUTH_TOKEN: "DUMMY"
      TWILIO_WHATSAPP_FROM: "whatsapp:+50700000000"
      CRON_SECRET: "DUMMY"

      # Hace el build más rápido en CI
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "apps/web/package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
